// <auto-generated />
namespace BibliotecaProjeto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _18_15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18_15));
        
        string IMigrationMetadata.Id
        {
            get { return "201806172115197_18_15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
